<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Country;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Country::firstOrCreate(['name' => 'Andorra', '2_digit' => 'AD', '3_digit' => 'AND']);
        Country::firstOrCreate(['name' => 'The United Arab Emirates', '2_digit' => 'AE', '3_digit' => 'ARE']);
        Country::firstOrCreate(['name' => 'Afghanistan', '2_digit' => 'AF', '3_digit' => 'AFG']);
        Country::firstOrCreate(['name' => 'Antigua and Barbuda', '2_digit' => 'AG', '3_digit' => 'ATG']);
        Country::firstOrCreate(['name' => 'Anguilla', '2_digit' => 'AI', '3_digit' => 'AIA']);
        Country::firstOrCreate(['name' => 'Albania', '2_digit' => 'AL', '3_digit' => 'ALB']);
        Country::firstOrCreate(['name' => 'Armenia', '2_digit' => 'AM', '3_digit' => 'ARM']);
        Country::firstOrCreate(['name' => 'Angola', '2_digit' => 'AO', '3_digit' => 'AGO']);
        Country::firstOrCreate(['name' => 'Antarctica', '2_digit' => 'AQ', '3_digit' => 'ATA']);
        Country::firstOrCreate(['name' => 'Argentina', '2_digit' => 'AR', '3_digit' => 'ARG']);
        Country::firstOrCreate(['name' => 'American Samoa', '2_digit' => 'AS', '3_digit' => 'ASM']);
        Country::firstOrCreate(['name' => 'Austria', '2_digit' => 'AT', '3_digit' => 'AUT']);
        Country::firstOrCreate(['name' => 'Australia', '2_digit' => 'AU', '3_digit' => 'AUS']);
        Country::firstOrCreate(['name' => 'Aruba', '2_digit' => 'AW', '3_digit' => 'ABW']);
        Country::firstOrCreate(['name' => 'Åland Islands', '2_digit' => 'AX', '3_digit' => 'ALA']);
        Country::firstOrCreate(['name' => 'Azerbaijan', '2_digit' => 'AZ', '3_digit' => 'AZE']);
        Country::firstOrCreate(['name' => 'Bosnia and Herzegovina', '2_digit' => 'BA', '3_digit' => 'BIH']);
        Country::firstOrCreate(['name' => 'Barbados', '2_digit' => 'BB', '3_digit' => 'BRB']);
        Country::firstOrCreate(['name' => 'Bangladesh', '2_digit' => 'BD', '3_digit' => 'BGD']);
        Country::firstOrCreate(['name' => 'Belgium', '2_digit' => 'BE', '3_digit' => 'BEL']);
        Country::firstOrCreate(['name' => 'Burkina Faso', '2_digit' => 'BF', '3_digit' => 'BFA']);
        Country::firstOrCreate(['name' => 'Bulgaria', '2_digit' => 'BG', '3_digit' => 'BGR']);
        Country::firstOrCreate(['name' => 'Bahrain', '2_digit' => 'BH', '3_digit' => 'BHR']);
        Country::firstOrCreate(['name' => 'Burundi', '2_digit' => 'BI', '3_digit' => 'BDI']);
        Country::firstOrCreate(['name' => 'Benin', '2_digit' => 'BJ', '3_digit' => 'BEN']);
        Country::firstOrCreate(['name' => 'Saint Barthélemy', '2_digit' => 'BL', '3_digit' => 'BLM']);
        Country::firstOrCreate(['name' => 'Bermuda', '2_digit' => 'BM', '3_digit' => 'BMU']);
        Country::firstOrCreate(['name' => 'Brunei Darussalam', '2_digit' => 'BN', '3_digit' => 'BRN']);
        Country::firstOrCreate(['name' => 'Plurinational State of Bolivia', '2_digit' => 'BO', '3_digit' => 'BOL']);
        Country::firstOrCreate(['name' => 'Bonaire Sint Eustatius Saba', '2_digit' => 'BQ', '3_digit' => 'BES']);
        Country::firstOrCreate(['name' => 'Brazil', '2_digit' => 'BR', '3_digit' => 'BRA']);
        Country::firstOrCreate(['name' => 'The Bahamas', '2_digit' => 'BS', '3_digit' => 'BHS']);
        Country::firstOrCreate(['name' => 'Bhutan', '2_digit' => 'BT', '3_digit' => 'BTN']);
        Country::firstOrCreate(['name' => 'Bouvet Island', '2_digit' => 'BV', '3_digit' => 'BVT']);
        Country::firstOrCreate(['name' => 'Botswana', '2_digit' => 'BW', '3_digit' => 'BWA']);
        Country::firstOrCreate(['name' => 'Belarus', '2_digit' => 'BY', '3_digit' => 'BLR']);
        Country::firstOrCreate(['name' => 'Belize', '2_digit' => 'BZ', '3_digit' => 'BLZ']);
        Country::firstOrCreate(['name' => 'Canada', '2_digit' => 'CA', '3_digit' => 'CAN']);
        Country::firstOrCreate(['name' => 'The Cocos (Keeling) Islands', '2_digit' => 'CC', '3_digit' => 'CCK']);
        Country::firstOrCreate(['name' => 'The Democratic Republic of the Congo', '2_digit' => 'CD', '3_digit' => 'COD']);
        Country::firstOrCreate(['name' => 'The Central African Republic', '2_digit' => 'CF', '3_digit' => 'CAF']);
        Country::firstOrCreate(['name' => 'The Congo', '2_digit' => 'CG', '3_digit' => 'COG']);
        Country::firstOrCreate(['name' => 'Switzerland', '2_digit' => 'CH', '3_digit' => 'CHE']);
        Country::firstOrCreate(['name' => 'Côte d\'Ivoire', '2_digit' => 'CI', '3_digit' => 'CIV']);
        Country::firstOrCreate(['name' => 'The Cook Islands', '2_digit' => 'CK', '3_digit' => 'COK']);
        Country::firstOrCreate(['name' => 'Chile', '2_digit' => 'CL', '3_digit' => 'CHL']);
        Country::firstOrCreate(['name' => 'Cameroon', '2_digit' => 'CM', '3_digit' => 'CMR']);
        Country::firstOrCreate(['name' => 'China', '2_digit' => 'CN', '3_digit' => 'CHN']);
        Country::firstOrCreate(['name' => 'Colombia', '2_digit' => 'CO', '3_digit' => 'COL']);
        Country::firstOrCreate(['name' => 'Costa Rica', '2_digit' => 'CR', '3_digit' => 'CRI']);
        Country::firstOrCreate(['name' => 'Cuba', '2_digit' => 'CU', '3_digit' => 'CUB']);
        Country::firstOrCreate(['name' => 'Cabo Verde', '2_digit' => 'CV', '3_digit' => 'CPV']);
        Country::firstOrCreate(['name' => 'Curaçao', '2_digit' => 'CW', '3_digit' => 'CUW']);
        Country::firstOrCreate(['name' => 'Christmas Island', '2_digit' => 'CX', '3_digit' => 'CXR']);
        Country::firstOrCreate(['name' => 'Cyprus', '2_digit' => 'CY', '3_digit' => 'CYP']);
        Country::firstOrCreate(['name' => 'Czechia', '2_digit' => 'CZ', '3_digit' => 'CZE']);
        Country::firstOrCreate(['name' => 'Germany', '2_digit' => 'DE', '3_digit' => 'DEU']);
        Country::firstOrCreate(['name' => 'Djibouti', '2_digit' => 'DJ', '3_digit' => 'DJI']);
        Country::firstOrCreate(['name' => 'Denmark', '2_digit' => 'DK', '3_digit' => 'DNK']);
        Country::firstOrCreate(['name' => 'Dominica', '2_digit' => 'DM', '3_digit' => 'DMA']);
        Country::firstOrCreate(['name' => 'The Dominican Republic', '2_digit' => 'DO', '3_digit' => 'DOM']);
        Country::firstOrCreate(['name' => 'Algeria', '2_digit' => 'DZ', '3_digit' => 'DZA']);
        Country::firstOrCreate(['name' => 'Ecuador', '2_digit' => 'EC', '3_digit' => 'ECU']);
        Country::firstOrCreate(['name' => 'Estonia', '2_digit' => 'EE', '3_digit' => 'EST']);
        Country::firstOrCreate(['name' => 'Egypt', '2_digit' => 'EG', '3_digit' => 'EGY']);
        Country::firstOrCreate(['name' => 'Western Sahara', '2_digit' => 'EH', '3_digit' => 'ESH']);
        Country::firstOrCreate(['name' => 'Eritrea', '2_digit' => 'ER', '3_digit' => 'ERI']);
        Country::firstOrCreate(['name' => 'Spain', '2_digit' => 'ES', '3_digit' => 'ESP']);
        Country::firstOrCreate(['name' => 'Ethiopia', '2_digit' => 'ET', '3_digit' => 'ETH']);
        Country::firstOrCreate(['name' => 'Finland', '2_digit' => 'FI', '3_digit' => 'FIN']);
        Country::firstOrCreate(['name' => 'Fiji', '2_digit' => 'FJ', '3_digit' => 'FJI']);
        Country::firstOrCreate(['name' => 'The Falkland Islands', '2_digit' => 'FK', '3_digit' => 'FLK']);
        Country::firstOrCreate(['name' => 'Federated States of Micronesia', '2_digit' => 'FM', '3_digit' => 'FSM']);
        Country::firstOrCreate(['name' => 'The Faroe Islands', '2_digit' => 'FO', '3_digit' => 'FRO']);
        Country::firstOrCreate(['name' => 'France', '2_digit' => 'FR', '3_digit' => 'FRA']);
        Country::firstOrCreate(['name' => 'Gabon', '2_digit' => 'GA', '3_digit' => 'GAB']);
        Country::firstOrCreate(['name' => 'The United Kingdom of Great Britain and Northern Ireland', '2_digit' => 'GB', '3_digit' => 'GBR']);
        Country::firstOrCreate(['name' => 'Grenada', '2_digit' => 'GD', '3_digit' => 'GRD']);
        Country::firstOrCreate(['name' => 'Georgia', '2_digit' => 'GE', '3_digit' => 'GEO']);
        Country::firstOrCreate(['name' => 'French Guiana', '2_digit' => 'GF', '3_digit' => 'GUF']);
        Country::firstOrCreate(['name' => 'Guernsey', '2_digit' => 'GG', '3_digit' => 'GGY']);
        Country::firstOrCreate(['name' => 'Ghana', '2_digit' => 'GH', '3_digit' => 'GHA']);
        Country::firstOrCreate(['name' => 'Gibraltar', '2_digit' => 'GI', '3_digit' => 'GIB']);
        Country::firstOrCreate(['name' => 'Greenland', '2_digit' => 'GL', '3_digit' => 'GRL']);
        Country::firstOrCreate(['name' => 'The Gambia', '2_digit' => 'GM', '3_digit' => 'GMB']);
        Country::firstOrCreate(['name' => 'Guinea', '2_digit' => 'GN', '3_digit' => 'GIN']);
        Country::firstOrCreate(['name' => 'Guadeloupe', '2_digit' => 'GP', '3_digit' => 'GLP']);
        Country::firstOrCreate(['name' => 'Equatorial Guinea', '2_digit' => 'GQ', '3_digit' => 'GNQ']);
        Country::firstOrCreate(['name' => 'Greece', '2_digit' => 'GR', '3_digit' => 'GRC']);
        Country::firstOrCreate(['name' => 'South Georgia and the South Sandwich Islands', '2_digit' => 'GS', '3_digit' => 'SGS']);
        Country::firstOrCreate(['name' => 'Guatemala', '2_digit' => 'GT', '3_digit' => 'GTM']);
        Country::firstOrCreate(['name' => 'Guam', '2_digit' => 'GU', '3_digit' => 'GUM']);
        Country::firstOrCreate(['name' => 'Guinea-Bissau', '2_digit' => 'GW', '3_digit' => 'GNB']);
        Country::firstOrCreate(['name' => 'Guyana', '2_digit' => 'GY', '3_digit' => 'GUY']);
        Country::firstOrCreate(['name' => 'Hong Kong', '2_digit' => 'HK', '3_digit' => 'HKG']);
        Country::firstOrCreate(['name' => 'Heard Island and McDonald Islands', '2_digit' => 'HM', '3_digit' => 'HMD']);
        Country::firstOrCreate(['name' => 'Honduras', '2_digit' => 'HN', '3_digit' => 'HND']);
        Country::firstOrCreate(['name' => 'Croatia', '2_digit' => 'HR', '3_digit' => 'HRV']);
        Country::firstOrCreate(['name' => 'Haiti', '2_digit' => 'HT', '3_digit' => 'HTI']);
        Country::firstOrCreate(['name' => 'Hungary', '2_digit' => 'HU', '3_digit' => 'HUN']);
        Country::firstOrCreate(['name' => 'Indonesia', '2_digit' => 'ID', '3_digit' => 'IDN']);
        Country::firstOrCreate(['name' => 'Ireland', '2_digit' => 'IE', '3_digit' => 'IRL']);
        Country::firstOrCreate(['name' => 'Israel', '2_digit' => 'IL', '3_digit' => 'ISR']);
        Country::firstOrCreate(['name' => 'Isle of Man', '2_digit' => 'IM', '3_digit' => 'IMN']);
        Country::firstOrCreate(['name' => 'India', '2_digit' => 'IN', '3_digit' => 'IND']);
        Country::firstOrCreate(['name' => 'The British Indian Ocean Territory', '2_digit' => 'IO', '3_digit' => 'IOT']);
        Country::firstOrCreate(['name' => 'Iraq', '2_digit' => 'IQ', '3_digit' => 'IRQ']);
        Country::firstOrCreate(['name' => 'Islamic Republic of Iran', '2_digit' => 'IR', '3_digit' => 'IRN']);
        Country::firstOrCreate(['name' => 'Iceland', '2_digit' => 'IS', '3_digit' => 'ISL']);
        Country::firstOrCreate(['name' => 'Italy', '2_digit' => 'IT', '3_digit' => 'ITA']);
        Country::firstOrCreate(['name' => 'Jersey', '2_digit' => 'JE', '3_digit' => 'JEY']);
        Country::firstOrCreate(['name' => 'Jamaica', '2_digit' => 'JM', '3_digit' => 'JAM']);
        Country::firstOrCreate(['name' => 'Jordan', '2_digit' => 'JO', '3_digit' => 'JOR']);
        Country::firstOrCreate(['name' => 'Japan', '2_digit' => 'JP', '3_digit' => 'JPN']);
        Country::firstOrCreate(['name' => 'Kenya', '2_digit' => 'KE', '3_digit' => 'KEN']);
        Country::firstOrCreate(['name' => 'Kyrgyzstan', '2_digit' => 'KG', '3_digit' => 'KGZ']);
        Country::firstOrCreate(['name' => 'Cambodia', '2_digit' => 'KH', '3_digit' => 'KHM']);
        Country::firstOrCreate(['name' => 'Kiribati', '2_digit' => 'KI', '3_digit' => 'KIR']);
        Country::firstOrCreate(['name' => 'Comoros', '2_digit' => 'KM', '3_digit' => 'COM']);
        Country::firstOrCreate(['name' => 'Saint Kitts and Nevis', '2_digit' => 'KN', '3_digit' => 'KNA']);
        Country::firstOrCreate(['name' => 'The Democratic People\'s Republic of Korea ', '2_digit' => 'KP', '3_digit' => 'PRK']);
        Country::firstOrCreate(['name' => 'The Republic of Korea', '2_digit' => 'KR', '3_digit' => 'KOR']);
        Country::firstOrCreate(['name' => 'Kuwait', '2_digit' => 'KW', '3_digit' => 'KWT']);
        Country::firstOrCreate(['name' => 'Cayman Islands', '2_digit' => 'KY', '3_digit' => 'CYM']);
        Country::firstOrCreate(['name' => 'Kazakhstan', '2_digit' => 'KZ', '3_digit' => 'KAZ']);
        Country::firstOrCreate(['name' => 'The Lao People\'s Democratic Republic', '2_digit' => 'LA', '3_digit' => 'LAO']);
        Country::firstOrCreate(['name' => 'Lebanon', '2_digit' => 'LB', '3_digit' => 'LBN']);
        Country::firstOrCreate(['name' => 'Saint Lucia', '2_digit' => 'LC', '3_digit' => 'LCA']);
        Country::firstOrCreate(['name' => 'Liechtenstein', '2_digit' => 'LI', '3_digit' => 'LIE']);
        Country::firstOrCreate(['name' => 'Sri Lanka', '2_digit' => 'LK', '3_digit' => 'LKA']);
        Country::firstOrCreate(['name' => 'Liberia', '2_digit' => 'LR', '3_digit' => 'LBR']);
        Country::firstOrCreate(['name' => 'Lesotho', '2_digit' => 'LS', '3_digit' => 'LSO']);
        Country::firstOrCreate(['name' => 'Lithuania', '2_digit' => 'LT', '3_digit' => 'LTU']);
        Country::firstOrCreate(['name' => 'Luxembourg', '2_digit' => 'LU', '3_digit' => 'LUX']);
        Country::firstOrCreate(['name' => 'Latvia', '2_digit' => 'LV', '3_digit' => 'LVA']);
        Country::firstOrCreate(['name' => 'Libya', '2_digit' => 'LY', '3_digit' => 'LBY']);
        Country::firstOrCreate(['name' => 'Morocco', '2_digit' => 'MA', '3_digit' => 'MAR']);
        Country::firstOrCreate(['name' => 'Monaco', '2_digit' => 'MC', '3_digit' => 'MCO']);
        Country::firstOrCreate(['name' => 'The Republic of Moldova', '2_digit' => 'MD', '3_digit' => 'MDA']);
        Country::firstOrCreate(['name' => 'Montenegro', '2_digit' => 'ME', '3_digit' => 'MNE']);
        Country::firstOrCreate(['name' => 'Saint Martin', '2_digit' => 'MF', '3_digit' => 'MAF']);
        Country::firstOrCreate(['name' => 'Madagascar', '2_digit' => 'MG', '3_digit' => 'MDG']);
        Country::firstOrCreate(['name' => 'The Marshall Islands', '2_digit' => 'MH', '3_digit' => 'MHL']);
        Country::firstOrCreate(['name' => 'North Macedonia', '2_digit' => 'MK', '3_digit' => 'MKD']);
        Country::firstOrCreate(['name' => 'Mali', '2_digit' => 'ML', '3_digit' => 'MLI']);
        Country::firstOrCreate(['name' => 'Myanmar', '2_digit' => 'MM', '3_digit' => 'MMR']);
        Country::firstOrCreate(['name' => 'Mongolia', '2_digit' => 'MN', '3_digit' => 'MNG']);
        Country::firstOrCreate(['name' => 'Macao', '2_digit' => 'MO', '3_digit' => 'MAC']);
        Country::firstOrCreate(['name' => 'The Northern Mariana Islands', '2_digit' => 'MP', '3_digit' => 'MNP']);
        Country::firstOrCreate(['name' => 'Martinique', '2_digit' => 'MQ', '3_digit' => 'MTQ']);
        Country::firstOrCreate(['name' => 'Mauritania', '2_digit' => 'MR', '3_digit' => 'MRT']);
        Country::firstOrCreate(['name' => 'Montserrat', '2_digit' => 'MS', '3_digit' => 'MSR']);
        Country::firstOrCreate(['name' => 'Malta', '2_digit' => 'MT', '3_digit' => 'MLT']);
        Country::firstOrCreate(['name' => 'Mauritius', '2_digit' => 'MU', '3_digit' => 'MUS']);
        Country::firstOrCreate(['name' => 'Maldives', '2_digit' => 'MV', '3_digit' => 'MDV']);
        Country::firstOrCreate(['name' => 'Malawi', '2_digit' => 'MW', '3_digit' => 'MWI']);
        Country::firstOrCreate(['name' => 'Mexico', '2_digit' => 'MX', '3_digit' => 'MEX']);
        Country::firstOrCreate(['name' => 'Malaysia', '2_digit' => 'MY', '3_digit' => 'MYS']);
        Country::firstOrCreate(['name' => 'Mozambique', '2_digit' => 'MZ', '3_digit' => 'MOZ']);
        Country::firstOrCreate(['name' => 'Namibia', '2_digit' => 'NA', '3_digit' => 'NAM']);
        Country::firstOrCreate(['name' => 'New Caledonia', '2_digit' => 'NC', '3_digit' => 'NCL']);
        Country::firstOrCreate(['name' => 'The Niger', '2_digit' => 'NE', '3_digit' => 'NER']);
        Country::firstOrCreate(['name' => 'Norfolk Island', '2_digit' => 'NF', '3_digit' => 'NFK']);
        Country::firstOrCreate(['name' => 'Nigeria', '2_digit' => 'NG', '3_digit' => 'NGA']);
        Country::firstOrCreate(['name' => 'Nicaragua', '2_digit' => 'NI', '3_digit' => 'NIC']);
        Country::firstOrCreate(['name' => 'The Netherlands', '2_digit' => 'NL', '3_digit' => 'NLD']);
        Country::firstOrCreate(['name' => 'Norway', '2_digit' => 'NO', '3_digit' => 'NOR']);
        Country::firstOrCreate(['name' => 'Nepal', '2_digit' => 'NP', '3_digit' => 'NPL']);
        Country::firstOrCreate(['name' => 'Nauru', '2_digit' => 'NR', '3_digit' => 'NRU']);
        Country::firstOrCreate(['name' => 'Niue', '2_digit' => 'NU', '3_digit' => 'NIU']);
        Country::firstOrCreate(['name' => 'New Zealand', '2_digit' => 'NZ', '3_digit' => 'NZL']);
        Country::firstOrCreate(['name' => 'Oman', '2_digit' => 'OM', '3_digit' => 'OMN']);
        Country::firstOrCreate(['name' => 'Panama', '2_digit' => 'PA', '3_digit' => 'PAN']);
        Country::firstOrCreate(['name' => 'Peru', '2_digit' => 'PE', '3_digit' => 'PER']);
        Country::firstOrCreate(['name' => 'French Polynesia', '2_digit' => 'PF', '3_digit' => 'PYF']);
        Country::firstOrCreate(['name' => 'Papua New Guinea', '2_digit' => 'PG', '3_digit' => 'PNG']);
        Country::firstOrCreate(['name' => 'Philippines', '2_digit' => 'PH', '3_digit' => 'PHL']);
        Country::firstOrCreate(['name' => 'Pakistan', '2_digit' => 'PK', '3_digit' => 'PAK']);
        Country::firstOrCreate(['name' => 'Poland', '2_digit' => 'PL', '3_digit' => 'POL']);
        Country::firstOrCreate(['name' => 'Saint Pierre and Miquelon', '2_digit' => 'PM', '3_digit' => 'SPM']);
        Country::firstOrCreate(['name' => 'Pitcairn', '2_digit' => 'PN', '3_digit' => 'PCN']);
        Country::firstOrCreate(['name' => 'Puerto Rico', '2_digit' => 'PR', '3_digit' => 'PRI']);
        Country::firstOrCreate(['name' => 'Palestine, State of', '2_digit' => 'PS', '3_digit' => 'PSE']);
        Country::firstOrCreate(['name' => 'Portugal', '2_digit' => 'PT', '3_digit' => 'PRT']);
        Country::firstOrCreate(['name' => 'Palau', '2_digit' => 'PW', '3_digit' => 'PLW']);
        Country::firstOrCreate(['name' => 'Paraguay', '2_digit' => 'PY', '3_digit' => 'PRY']);
        Country::firstOrCreate(['name' => 'Qatar', '2_digit' => 'QA', '3_digit' => 'QAT']);
        Country::firstOrCreate(['name' => 'Réunion', '2_digit' => 'RE', '3_digit' => 'REU']);
        Country::firstOrCreate(['name' => 'Romania', '2_digit' => 'RO', '3_digit' => 'ROU']);
        Country::firstOrCreate(['name' => 'Serbia', '2_digit' => 'RS', '3_digit' => 'SRB']);
        Country::firstOrCreate(['name' => 'Russian Federation', '2_digit' => 'RU', '3_digit' => 'RUS']);
        Country::firstOrCreate(['name' => 'Rwanda', '2_digit' => 'RW', '3_digit' => 'RWA']);
        Country::firstOrCreate(['name' => 'Saudi Arabia', '2_digit' => 'SA', '3_digit' => 'SAU']);
        Country::firstOrCreate(['name' => 'Solomon Islands', '2_digit' => 'SB', '3_digit' => 'SLB']);
        Country::firstOrCreate(['name' => 'Seychelles', '2_digit' => 'SC', '3_digit' => 'SYC']);
        Country::firstOrCreate(['name' => 'Sudan', '2_digit' => 'SD', '3_digit' => 'SDN']);
        Country::firstOrCreate(['name' => 'Sweden', '2_digit' => 'SE', '3_digit' => 'SWE']);
        Country::firstOrCreate(['name' => 'Singapore', '2_digit' => 'SG', '3_digit' => 'SGP']);
        Country::firstOrCreate(['name' => 'Saint Helena Ascension Island Tristan da Cunha', '2_digit' => 'SH', '3_digit' => 'SHN']);
        Country::firstOrCreate(['name' => 'Slovenia', '2_digit' => 'SI', '3_digit' => 'SVN']);
        Country::firstOrCreate(['name' => 'Svalbard Jan Mayen', '2_digit' => 'SJ', '3_digit' => 'SJM']);
        Country::firstOrCreate(['name' => 'Slovakia', '2_digit' => 'SK', '3_digit' => 'SVK']);
        Country::firstOrCreate(['name' => 'Sierra Leone', '2_digit' => 'SL', '3_digit' => 'SLE']);
        Country::firstOrCreate(['name' => 'San Marino', '2_digit' => 'SM', '3_digit' => 'SMR']);
        Country::firstOrCreate(['name' => 'Senegal', '2_digit' => 'SN', '3_digit' => 'SEN']);
        Country::firstOrCreate(['name' => 'Somalia', '2_digit' => 'SO', '3_digit' => 'SOM']);
        Country::firstOrCreate(['name' => 'Suriname', '2_digit' => 'SR', '3_digit' => 'SUR']);
        Country::firstOrCreate(['name' => 'South Sudan', '2_digit' => 'SS', '3_digit' => 'SSD']);
        Country::firstOrCreate(['name' => 'Sao Tome and Principe', '2_digit' => 'ST', '3_digit' => 'STP']);
        Country::firstOrCreate(['name' => 'El Salvador', '2_digit' => 'SV', '3_digit' => 'SLV']);
        Country::firstOrCreate(['name' => 'Sint Maarten', '2_digit' => 'SX', '3_digit' => 'SXM']);
        Country::firstOrCreate(['name' => 'Syrian Arab Republic', '2_digit' => 'SY', '3_digit' => 'SYR']);
        Country::firstOrCreate(['name' => 'Eswatini', '2_digit' => 'SZ', '3_digit' => 'SWZ']);
        Country::firstOrCreate(['name' => 'Turks and Caicos Islands', '2_digit' => 'TC', '3_digit' => 'TCA']);
        Country::firstOrCreate(['name' => 'Chad', '2_digit' => 'TD', '3_digit' => 'TCD']);
        Country::firstOrCreate(['name' => 'French Southern Territories', '2_digit' => 'TF', '3_digit' => 'ATF']);
        Country::firstOrCreate(['name' => 'Togo', '2_digit' => 'TG', '3_digit' => 'TGO']);
        Country::firstOrCreate(['name' => 'Thailand', '2_digit' => 'TH', '3_digit' => 'THA']);
        Country::firstOrCreate(['name' => 'Tajikistan', '2_digit' => 'TJ', '3_digit' => 'TJK']);
        Country::firstOrCreate(['name' => 'Tokelau', '2_digit' => 'TK', '3_digit' => 'TKL']);
        Country::firstOrCreate(['name' => 'Timor-Leste', '2_digit' => 'TL', '3_digit' => 'TLS']);
        Country::firstOrCreate(['name' => 'Turkmenistan', '2_digit' => 'TM', '3_digit' => 'TKM']);
        Country::firstOrCreate(['name' => 'Tunisia', '2_digit' => 'TN', '3_digit' => 'TUN']);
        Country::firstOrCreate(['name' => 'Tonga', '2_digit' => 'TO', '3_digit' => 'TON']);
        Country::firstOrCreate(['name' => 'Turkey', '2_digit' => 'TR', '3_digit' => 'TUR']);
        Country::firstOrCreate(['name' => 'Trinidad and Tobago', '2_digit' => 'TT', '3_digit' => 'TTO']);
        Country::firstOrCreate(['name' => 'Tuvalu', '2_digit' => 'TV', '3_digit' => 'TUV']);
        Country::firstOrCreate(['name' => 'Taiwan', '2_digit' => 'TW', '3_digit' => 'TWN']);
        Country::firstOrCreate(['name' => 'Tanzania', '2_digit' => 'TZ', '3_digit' => 'TZA']);
        Country::firstOrCreate(['name' => 'Ukraine', '2_digit' => 'UA', '3_digit' => 'UKR']);
        Country::firstOrCreate(['name' => 'Uganda', '2_digit' => 'UG', '3_digit' => 'UGA']);
        Country::firstOrCreate(['name' => 'United States Minor Outlying Islands', '2_digit' => 'UM', '3_digit' => 'UMI']);
        Country::firstOrCreate(['name' => 'United States of America', '2_digit' => 'US', '3_digit' => 'USA']);
        Country::firstOrCreate(['name' => 'Uruguay', '2_digit' => 'UY', '3_digit' => 'URY']);
        Country::firstOrCreate(['name' => 'Uzbekistan', '2_digit' => 'UZ', '3_digit' => 'UZB']);
        Country::firstOrCreate(['name' => 'Holy See', '2_digit' => 'VA', '3_digit' => 'VAT']);
        Country::firstOrCreate(['name' => 'Saint Vincent and the Grenadines', '2_digit' => 'VC', '3_digit' => 'VCT']);
        Country::firstOrCreate(['name' => 'Venezuela', '2_digit' => 'VE', '3_digit' => 'VEN']);
        Country::firstOrCreate(['name' => 'Virgin Islands (British)', '2_digit' => 'VG', '3_digit' => 'VGB']);
        Country::firstOrCreate(['name' => 'Virgin Islands (U.S.)', '2_digit' => 'VI', '3_digit' => 'VIR']);
        Country::firstOrCreate(['name' => 'Viet Nam', '2_digit' => 'VN', '3_digit' => 'VNM']);
        Country::firstOrCreate(['name' => 'Vanuatu', '2_digit' => 'VU', '3_digit' => 'VUT']);
        Country::firstOrCreate(['name' => 'Wallis and Futuna', '2_digit' => 'WF', '3_digit' => 'WLF']);
        Country::firstOrCreate(['name' => 'Samoa', '2_digit' => 'WS', '3_digit' => 'WSM']);
        Country::firstOrCreate(['name' => 'Yemen', '2_digit' => 'YE', '3_digit' => 'YEM']);
        Country::firstOrCreate(['name' => 'Mayotte', '2_digit' => 'YT', '3_digit' => 'MYT']);
        Country::firstOrCreate(['name' => 'South Africa', '2_digit' => 'ZA', '3_digit' => 'ZAF']);
        Country::firstOrCreate(['name' => 'Zambia', '2_digit' => 'ZM', '3_digit' => 'ZMB']);
        Country::firstOrCreate(['name' => 'Zimbabwe', '2_digit' => 'ZW' , '3_digit' => 'ZWE']);
    }
}
