<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Language;

class LanguageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Language::firstOrCreate(['3_digit' => 'aar', '2_digit' => 'aa', 'name' => 'Afar']);
        Language::firstOrCreate(['3_digit' => 'abk', '2_digit' => 'ab', 'name' => 'Abkhazian']);
        Language::firstOrCreate(['3_digit' => 'ace', '2_digit' => '', 'name' => 'Achinese']);
        Language::firstOrCreate(['3_digit' => 'ach', '2_digit' => '', 'name' => 'Acoli']);
        Language::firstOrCreate(['3_digit' => 'ada', '2_digit' => '', 'name' => 'Adangme']);
        Language::firstOrCreate(['3_digit' => 'ady', '2_digit' => '', 'name' => 'Adyghe / Adygei']);
        Language::firstOrCreate(['3_digit' => 'afa', '2_digit' => '', 'name' => 'Afro-Asiatic languages']);
        Language::firstOrCreate(['3_digit' => 'afh', '2_digit' => '', 'name' => 'Afrihili']);
        Language::firstOrCreate(['3_digit' => 'afr', '2_digit' => 'af', 'name' => 'Afrikaans']);
        Language::firstOrCreate(['3_digit' => 'ain', '2_digit' => '', 'name' => 'Ainu']);
        Language::firstOrCreate(['3_digit' => 'aka', '2_digit' => '', 'name' => 'Akan']);
        Language::firstOrCreate(['3_digit' => 'akk', '2_digit' => '', 'name' => 'Akkadian']);
        Language::firstOrCreate(['3_digit' => 'alb', '2_digit' => 'sq', 'name' => 'Albanian']);
        Language::firstOrCreate(['3_digit' => 'sqi', '2_digit' => 'sq', 'name' => 'Albanian']);
        Language::firstOrCreate(['3_digit' => 'ale', '2_digit' => '', 'name' => 'Aleut']);
        Language::firstOrCreate(['3_digit' => 'alg', '2_digit' => '', 'name' => 'Algonquian languages']);
        Language::firstOrCreate(['3_digit' => 'alt', '2_digit' => '', 'name' => 'Southern Altai']);
        Language::firstOrCreate(['3_digit' => 'amh', '2_digit' => 'am', 'name' => 'Amharic']);
        Language::firstOrCreate(['3_digit' => 'ang', '2_digit' => '', 'name' => 'English, Old (ca.450-1100)']);
        Language::firstOrCreate(['3_digit' => 'anp', '2_digit' => '', 'name' => 'Angika']);
        Language::firstOrCreate(['3_digit' => 'apa', '2_digit' => '', 'name' => 'Apache languages']);
        Language::firstOrCreate(['3_digit' => 'ara', '2_digit' => 'ar', 'name' => 'Arabic']);
        Language::firstOrCreate(['3_digit' => 'arc', '2_digit' => '', 'name' => 'Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)']);
        Language::firstOrCreate(['3_digit' => 'arg', '2_digit' => 'an', 'name' => 'Aragonese']);
        Language::firstOrCreate(['3_digit' => 'arm', '2_digit' => 'hy', 'name' => 'Armenian']);
        Language::firstOrCreate(['3_digit' => 'hye', '2_digit' => 'hy', 'name' => 'Armenian']);
        Language::firstOrCreate(['3_digit' => 'arn', '2_digit' => '', 'name' => 'Mapudungun / Mapuche']);
        Language::firstOrCreate(['3_digit' => 'arp', '2_digit' => '', 'name' => 'Arapaho']);
        Language::firstOrCreate(['3_digit' => 'art','2_digit' => '', 'name' => 'Artificial languages']);
        Language::firstOrCreate(['3_digit' => 'arw','2_digit' => '', 'name' => 'Arawak']);
        Language::firstOrCreate(['3_digit' => 'asm','2_digit' => 'as', 'name' => 'Assamese']);
        Language::firstOrCreate(['3_digit' => 'ast','2_digit' => '', 'name' => 'Asturian; Bable; Leonese; Asturleonese']);
        Language::firstOrCreate(['3_digit' => 'ath','2_digit' => '', 'name' => 'Athapascan languages']);
        Language::firstOrCreate(['3_digit' => 'aus','2_digit' => '', 'name' => 'Australian languages']);
        Language::firstOrCreate(['3_digit' => 'ava','2_digit' => 'av', 'name' => 'Avaric']);
        Language::firstOrCreate(['3_digit' => 'ave','2_digit' => 'ae', 'name' => 'Avestan']);
        Language::firstOrCreate(['3_digit' => 'awa','2_digit' => '', 'name' => 'Awadhi']);
        Language::firstOrCreate(['3_digit' => 'aym','2_digit' => 'ay', 'name' => 'Aymara']);
        Language::firstOrCreate(['3_digit' => 'aze','2_digit' => 'az', 'name' => 'Azerbaijani']);
        Language::firstOrCreate(['3_digit' => 'bad','2_digit' => '', 'name' => 'Banda languages']);
        Language::firstOrCreate(['3_digit' => 'bai','2_digit' => '', 'name' => 'Bamileke languages']);
        Language::firstOrCreate(['3_digit' => 'bak','2_digit' => 'ba', 'name' => 'Bashkir']);
        Language::firstOrCreate(['3_digit' => 'bal','2_digit' => '', 'name' => 'Baluchi']);
        Language::firstOrCreate(['3_digit' => 'bam','2_digit' => 'bm', 'name' => 'Bambara']);
        Language::firstOrCreate(['3_digit' => 'ban','2_digit' => '', 'name' => 'Balinese']);
        Language::firstOrCreate(['3_digit' => 'baq','2_digit' => 'eu', 'name' => 'Basque']);
        Language::firstOrCreate(['3_digit' => 'eus','2_digit' => 'eu', 'name' => 'Basque']);
        Language::firstOrCreate(['3_digit' => 'bas','2_digit' => '', 'name' => 'Basa']);
        Language::firstOrCreate(['3_digit' => 'bat','2_digit' => '', 'name' => 'Baltic languages']);
        Language::firstOrCreate(['3_digit' => 'bej','2_digit' => '', 'name' => 'Beja; Bedawiyet']);
        Language::firstOrCreate(['3_digit' => 'bel','2_digit' => 'be', 'name' => 'Belarusian']);
        Language::firstOrCreate(['3_digit' => 'bem','2_digit' => '', 'name' => 'Bemba']);
        Language::firstOrCreate(['3_digit' => 'ben','2_digit' => 'bn', 'name' => 'Bengali']);
        Language::firstOrCreate(['3_digit' => 'ber','2_digit' => '', 'name' => 'Berber languages']);
        Language::firstOrCreate(['3_digit' => 'bho','2_digit' => '', 'name' => 'Bhojpuri']);
        Language::firstOrCreate(['3_digit' => 'bih','2_digit' => 'bh', 'name' => 'Bihari languages']);
        Language::firstOrCreate(['3_digit' => 'bik','2_digit' => '', 'name' => 'Bikol']);
        Language::firstOrCreate(['3_digit' => 'bin','2_digit' => '', 'name' => 'Bini; Edo']);
        Language::firstOrCreate(['3_digit' => 'bis','2_digit' => 'bi', 'name' => 'Bislama']);
        Language::firstOrCreate(['3_digit' => 'bla','2_digit' => '', 'name' => 'Siksika']);
        Language::firstOrCreate(['3_digit' => 'bnt','2_digit' => '', 'name' => 'Bantu languages']);
        Language::firstOrCreate(['3_digit' => 'tib','2_digit' => 'bo', 'name' => 'Tibetan']);
        Language::firstOrCreate(['3_digit' => 'bod','2_digit' => 'bo', 'name' => 'Tibetan']);
        Language::firstOrCreate(['3_digit' => 'bos','2_digit' => 'bs', 'name' => 'Bosnian']);
        Language::firstOrCreate(['3_digit' => 'bra','2_digit' => '', 'name' => 'Braj']);
        Language::firstOrCreate(['3_digit' => 'bre','2_digit' => 'br', 'name' => 'Breton']);
        Language::firstOrCreate(['3_digit' => 'btk','2_digit' => '', 'name' => 'Batak languages']);
        Language::firstOrCreate(['3_digit' => 'bua','2_digit' => '', 'name' => 'Buriat']);
        Language::firstOrCreate(['3_digit' => 'bug','2_digit' => '', 'name' => 'Buginese']);
        Language::firstOrCreate(['3_digit' => 'bul','2_digit' => 'bg', 'name' => 'Bulgarian']);
        Language::firstOrCreate(['3_digit' => 'bur','2_digit' => 'my', 'name' => 'Burmese']);
        Language::firstOrCreate(['3_digit' => 'mya','2_digit' => 'my', 'name' => 'Burmese']);
        Language::firstOrCreate(['3_digit' => 'byn','2_digit' => '', 'name' => 'Blin; Bilin']);
        Language::firstOrCreate(['3_digit' => 'cad','2_digit' => '', 'name' => 'Caddo']);
        Language::firstOrCreate(['3_digit' => 'cai','2_digit' => '', 'name' => 'Central American Indian languages']);
        Language::firstOrCreate(['3_digit' => 'car','2_digit' => '', 'name' => 'Galibi Carib']);
        Language::firstOrCreate(['3_digit' => 'cat','2_digit' => 'ca', 'name' => 'Catalan; Valencian']);
        Language::firstOrCreate(['3_digit' => 'cau','2_digit' => '', 'name' => 'Caucasian languages']);
        Language::firstOrCreate(['3_digit' => 'ceb','2_digit' => '', 'name' => 'Cebuano']);
        Language::firstOrCreate(['3_digit' => 'cel','2_digit' => '', 'name' => 'Celtic languages']);
        Language::firstOrCreate(['3_digit' => 'cze','2_digit' => 'cs', 'name' => 'Czech']);
        Language::firstOrCreate(['3_digit' => 'ces','2_digit' => 'cs', 'name' => 'Czech']);
        Language::firstOrCreate(['3_digit' => 'cha','2_digit' => 'ch', 'name' => 'Chamorro']);
        Language::firstOrCreate(['3_digit' => 'chb','2_digit' => '', 'name' => 'Chibcha']);
        Language::firstOrCreate(['3_digit' => 'che','2_digit' => 'ce', 'name' => 'Chechen']);
        Language::firstOrCreate(['3_digit' => 'chg','2_digit' => '', 'name' => 'Chagatai']);
        Language::firstOrCreate(['3_digit' => 'chi','2_digit' => 'zh', 'name' => 'Chinese']);
        Language::firstOrCreate(['3_digit' => 'zho','2_digit' => 'zh', 'name' => 'Chinese']);
        Language::firstOrCreate(['3_digit' => 'chk','2_digit' => '', 'name' => 'Chuukese']);
        Language::firstOrCreate(['3_digit' => 'chm','2_digit' => '', 'name' => 'Mari']);
        Language::firstOrCreate(['3_digit' => 'chn','2_digit' => '', 'name' => 'Chinook jargon']);
        Language::firstOrCreate(['3_digit' => 'cho','2_digit' => '', 'name' => 'Choctaw']);
        Language::firstOrCreate(['3_digit' => 'chp','2_digit' => '', 'name' => 'Chipewyan; Dene Suline']);
        Language::firstOrCreate(['3_digit' => 'chr','2_digit' => '', 'name' => 'Cherokee']);
        Language::firstOrCreate(['3_digit' => 'chu','2_digit' => 'cu', 'name' => 'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic']);
        Language::firstOrCreate(['3_digit' => 'chv','2_digit' => 'cv', 'name' => 'Chuvash']);
        Language::firstOrCreate(['3_digit' => 'chy','2_digit' => '', 'name' => 'Cheyenne']);
        Language::firstOrCreate(['3_digit' => 'cmc','2_digit' => '', 'name' => 'Chamic languages']);
        Language::firstOrCreate(['3_digit' => 'cnr','2_digit' => '', 'name' => 'Montenegrin']);
        Language::firstOrCreate(['3_digit' => 'cop','2_digit' => '', 'name' => 'Coptic']);
        Language::firstOrCreate(['3_digit' => 'cor','2_digit' => 'kw', 'name' => 'Cornish']);
        Language::firstOrCreate(['3_digit' => 'cos','2_digit' => 'co', 'name' => 'Corsican']);
        Language::firstOrCreate(['3_digit' => 'cpe','2_digit' => '', 'name' => 'Creoles and pidgins, English based']);
        Language::firstOrCreate(['3_digit' => 'cpf','2_digit' => '', 'name' => 'Creoles and pidgins, French-based']);
        Language::firstOrCreate(['3_digit' => 'cpp','2_digit' => '', 'name' => 'Creoles and pidgins, Portuguese-based']);
        Language::firstOrCreate(['3_digit' => 'cre','2_digit' => 'cr', 'name' => 'Cree']);
        Language::firstOrCreate(['3_digit' => 'crh','2_digit' => '', 'name' => 'Crimean Tatar; Crimean Turkish']);
        Language::firstOrCreate(['3_digit' => 'crp','2_digit' => '', 'name' => 'Creoles and pidgins']);
        Language::firstOrCreate(['3_digit' => 'csb','2_digit' => '', 'name' => 'Kashubian']);
        Language::firstOrCreate(['3_digit' => 'cus','2_digit' => '', 'name' => 'Cushitic languages']);
        Language::firstOrCreate(['3_digit' => 'wel','2_digit' => 'cy', 'name' => 'Welsh']);
        Language::firstOrCreate(['3_digit' => 'cym','2_digit' => 'cy', 'name' => 'Welsh']);
        Language::firstOrCreate(['3_digit' => 'cze','2_digit' => 'cs', 'name' => 'Czech']);
        Language::firstOrCreate(['3_digit' => 'ces','2_digit' => 'cs', 'name' => 'Czech']);
        Language::firstOrCreate(['3_digit' => 'dak','2_digit' => '', 'name' => 'Dakota']);
        Language::firstOrCreate(['3_digit' => 'dan','2_digit' => 'da', 'name' => 'Danish']);
        Language::firstOrCreate(['3_digit' => 'dar','2_digit' => '', 'name' => 'Dargwa']);
        Language::firstOrCreate(['3_digit' => 'day','2_digit' => '', 'name' => 'Land Dayak languages']);
        Language::firstOrCreate(['3_digit' => 'del','2_digit' => '', 'name' => 'Delaware']);
        Language::firstOrCreate(['3_digit' => 'den','2_digit' => '', 'name' => 'Slave (Athapascan)']);
        Language::firstOrCreate(['3_digit' => 'ger','2_digit' => 'de', 'name' => 'German']);
        Language::firstOrCreate(['3_digit' => 'deu','2_digit' => 'de', 'name' => 'German']);
        Language::firstOrCreate(['3_digit' => 'dgr','2_digit' => '', 'name' => 'Dogrib']);
        Language::firstOrCreate(['3_digit' => 'din','2_digit' => '', 'name' => 'Dinka']);
        Language::firstOrCreate(['3_digit' => 'div','2_digit' => 'dv', 'name' => 'Divehi; Dhivehi; Maldivian']);
        Language::firstOrCreate(['3_digit' => 'doi','2_digit' => '', 'name' => 'Dogri']);
        Language::firstOrCreate(['3_digit' => 'dra','2_digit' => '', 'name' => 'Dravidian languages']);
        Language::firstOrCreate(['3_digit' => 'dsb','2_digit' => '', 'name' => 'Lower Sorbian']);
        Language::firstOrCreate(['3_digit' => 'dua','2_digit' => '', 'name' => 'Duala']);
        Language::firstOrCreate(['3_digit' => 'dum','2_digit' => '', 'name' => 'Dutch, Middle (ca.1050-1350)']);
        Language::firstOrCreate(['3_digit' => 'dut','2_digit' => 'nl', 'name' => 'Dutch; Flemish']);
        Language::firstOrCreate(['3_digit' => 'nld','2_digit' => 'nl', 'name' => 'Dutch; Flemish']);
        Language::firstOrCreate(['3_digit' => 'dyu','2_digit' => '', 'name' => 'Dyula']);
        Language::firstOrCreate(['3_digit' => 'dzo','2_digit' => 'dz', 'name' => 'Dzongkha']);
        Language::firstOrCreate(['3_digit' => 'efi','2_digit' => '', 'name' => 'Efik']);
        Language::firstOrCreate(['3_digit' => 'egy','2_digit' => '', 'name' => 'Egyptian (Ancient)']);
        Language::firstOrCreate(['3_digit' => 'eka','2_digit' => '', 'name' => 'Ekajuk']);
        Language::firstOrCreate(['3_digit' => 'gre','2_digit' => 'el', 'name' => 'Greek, Modern (1453-)']);
        Language::firstOrCreate(['3_digit' => 'ell','2_digit' => 'el', 'name' => 'Greek, Modern (1453-)']);
        Language::firstOrCreate(['3_digit' => 'elx','2_digit' => '', 'name' => 'Elamite']);
        Language::firstOrCreate(['3_digit' => 'eng','2_digit' => 'en', 'name' => 'English']);
        Language::firstOrCreate(['3_digit' => 'enm','2_digit' => '', 'name' => 'English, Middle (1100-1500)']);
        Language::firstOrCreate(['3_digit' => 'epo','2_digit' => 'eo', 'name' => 'Esperanto']);
        Language::firstOrCreate(['3_digit' => 'est','2_digit' => 'et', 'name' => 'Estonian']);
        Language::firstOrCreate(['3_digit' => 'baq','2_digit' => 'eu', 'name' => 'Basque']);
        Language::firstOrCreate(['3_digit' => 'eus','2_digit' => 'eu', 'name' => 'Basque']);
        Language::firstOrCreate(['3_digit' => 'ewe','2_digit' => 'ee', 'name' => 'Ewe']);
        Language::firstOrCreate(['3_digit' => 'ewo','2_digit' => '', 'name' => 'Ewondo']);
        Language::firstOrCreate(['3_digit' => 'fan','2_digit' => '', 'name' => 'Fang']);
        Language::firstOrCreate(['3_digit' => 'fao','2_digit' => 'fo', 'name' => 'Faroese']);
        Language::firstOrCreate(['3_digit' => 'per','2_digit' => 'fa', 'name' => 'Persian']);
        Language::firstOrCreate(['3_digit' => 'fas','2_digit' => 'fa', 'name' => 'Persian']);
        Language::firstOrCreate(['3_digit' => 'fat','2_digit' => '', 'name' => 'Fanti']);
        Language::firstOrCreate(['3_digit' => 'fij','2_digit' => 'fj', 'name' => 'Fijian']);
        Language::firstOrCreate(['3_digit' => 'fil','2_digit' => '', 'name' => 'Filipino; Pilipino']);
        Language::firstOrCreate(['3_digit' => 'fin','2_digit' => 'fi', 'name' => 'Finnish']);
        Language::firstOrCreate(['3_digit' => 'fiu','2_digit' => '', 'name' => 'Finno-Ugrian languages']);
        Language::firstOrCreate(['3_digit' => 'fon','2_digit' => '', 'name' => 'Fon']);
        Language::firstOrCreate(['3_digit' => 'fre','2_digit' => 'fr', 'name' => 'French']);
        Language::firstOrCreate(['3_digit' => 'fra','2_digit' => 'fr', 'name' => 'French']);
        Language::firstOrCreate(['3_digit' => 'frm','2_digit' => '', 'name' => 'French, Middle (ca.1400-1600)']);
        Language::firstOrCreate(['3_digit' => 'fro','2_digit' => '', 'name' => 'French, Old (842-ca.1400)']);
        Language::firstOrCreate(['3_digit' => 'frr','2_digit' => '', 'name' => 'Northern Frisian']);
        Language::firstOrCreate(['3_digit' => 'frs','2_digit' => '', 'name' => 'Eastern Frisian']);
        Language::firstOrCreate(['3_digit' => 'fry','2_digit' => 'fy', 'name' => 'Western Frisian']);
        Language::firstOrCreate(['3_digit' => 'ful','2_digit' => 'ff', 'name' => 'Fulah']);
        Language::firstOrCreate(['3_digit' => 'fur','2_digit' => '', 'name' => 'Friulian']);
        Language::firstOrCreate(['3_digit' => 'gaa','2_digit' => '', 'name' => 'Ga']);
        Language::firstOrCreate(['3_digit' => 'gay','2_digit' => '', 'name' => 'Gayo']);
        Language::firstOrCreate(['3_digit' => 'gba','2_digit' => '', 'name' => 'Gbaya']);
        Language::firstOrCreate(['3_digit' => 'gem','2_digit' => '', 'name' => 'Germanic languages']);
        Language::firstOrCreate(['3_digit' => 'geo','2_digit' => 'ka', 'name' => 'Georgian']);
        Language::firstOrCreate(['3_digit' => 'kat','2_digit' => 'ka', 'name' => 'Georgian']);
        Language::firstOrCreate(['3_digit' => 'ger','2_digit' => 'de', 'name' => 'German']);
        Language::firstOrCreate(['3_digit' => 'deu','2_digit' => 'de', 'name' => 'German']);
        Language::firstOrCreate(['3_digit' => 'gez','2_digit' => '', 'name' => 'Geez']);
        Language::firstOrCreate(['3_digit' => 'gil','2_digit' => '', 'name' => 'Gilbertese']);
        Language::firstOrCreate(['3_digit' => 'gla','2_digit' => 'gd', 'name' => 'Gaelic; Scottish Gaelic']);
        Language::firstOrCreate(['3_digit' => 'gle','2_digit' => 'ga', 'name' => 'Irish']);
        Language::firstOrCreate(['3_digit' => 'glg','2_digit' => 'gl', 'name' => 'Galician']);
        Language::firstOrCreate(['3_digit' => 'glv','2_digit' => 'gv', 'name' => 'Manx']);
        Language::firstOrCreate(['3_digit' => 'gmh','2_digit' => '', 'name' => 'German, Middle High (ca.1050-1500)']);
        Language::firstOrCreate(['3_digit' => 'goh','2_digit' => '', 'name' => 'German, Old High (ca.750-1050)']);
        Language::firstOrCreate(['3_digit' => 'gon','2_digit' => '', 'name' => 'Gondi']);
        Language::firstOrCreate(['3_digit' => 'gor','2_digit' => '', 'name' => 'Gorontalo']);
        Language::firstOrCreate(['3_digit' => 'got','2_digit' => '', 'name' => 'Gothic']);
        Language::firstOrCreate(['3_digit' => 'grb','2_digit' => '', 'name' => 'Grebo']);
        Language::firstOrCreate(['3_digit' => 'grc','2_digit' => '', 'name' => 'Greek, Ancient (to 1453)']);
        Language::firstOrCreate(['3_digit' => 'gre','2_digit' => 'el', 'name' => 'Greek, Modern (1453-)']);
        Language::firstOrCreate(['3_digit' => 'ell','2_digit' => 'el', 'name' => 'Greek, Modern (1453-)']);
        Language::firstOrCreate(['3_digit' => 'grn','2_digit' => 'gn', 'name' => 'Guarani']);
        Language::firstOrCreate(['3_digit' => 'gsw','2_digit' => '', 'name' => 'Swiss German; Alemannic; Alsatian']);
        Language::firstOrCreate(['3_digit' => 'guj','2_digit' => 'gu', 'name' => 'Gujarati']);
        Language::firstOrCreate(['3_digit' => 'gwi','2_digit' => '', 'name' => 'Gwich\'in']);
        Language::firstOrCreate(['3_digit' => 'hai','2_digit' => '', 'name' => 'Haida']);
        Language::firstOrCreate(['3_digit' => 'hat','2_digit' => 'ht', 'name' => 'Haitian; Haitian Creole']);
        Language::firstOrCreate(['3_digit' => 'hau','2_digit' => 'ha', 'name' => 'Hausa']);
        Language::firstOrCreate(['3_digit' => 'haw','2_digit' => '', 'name' => 'Hawaiian']);
        Language::firstOrCreate(['3_digit' => 'heb','2_digit' => 'he', 'name' => 'Hebrew']);
        Language::firstOrCreate(['3_digit' => 'her','2_digit' => 'hz', 'name' => 'Herero']);
        Language::firstOrCreate(['3_digit' => 'hil','2_digit' => '', 'name' => 'Hiligaynon']);
        Language::firstOrCreate(['3_digit' => 'him','2_digit' => '', 'name' => 'Himachali languages; Western Pahari languages']);
        Language::firstOrCreate(['3_digit' => 'hin','2_digit' => 'hi', 'name' => 'Hindi']);
        Language::firstOrCreate(['3_digit' => 'hit','2_digit' => '', 'name' => 'Hittite']);
        Language::firstOrCreate(['3_digit' => 'hmn','2_digit' => '', 'name' => 'Hmong; Mong']);
        Language::firstOrCreate(['3_digit' => 'hmo','2_digit' => 'ho', 'name' => 'Hiri Motu']);
        Language::firstOrCreate(['3_digit' => 'hrv','2_digit' => 'hr', 'name' => 'Croatian']);
        Language::firstOrCreate(['3_digit' => 'hsb','2_digit' => '', 'name' => 'Upper Sorbian']);
        Language::firstOrCreate(['3_digit' => 'hun','2_digit' => 'hu', 'name' => 'Hungarian']);
        Language::firstOrCreate(['3_digit' => 'hup','2_digit' => '', 'name' => 'Hupa']);
        Language::firstOrCreate(['3_digit' => 'arm','2_digit' => 'hy', 'name' => 'Armenian']);
        Language::firstOrCreate(['3_digit' => 'hye','2_digit' => 'hy', 'name' => 'Armenian']);
        Language::firstOrCreate(['3_digit' => 'iba','2_digit' => '', 'name' => 'Iban']);
        Language::firstOrCreate(['3_digit' => 'ibo','2_digit' => 'ig', 'name' => 'Igbo']);
        Language::firstOrCreate(['3_digit' => 'ice','2_digit' => 'is', 'name' => 'Icelandic']);
        Language::firstOrCreate(['3_digit' => 'isl','2_digit' => 'is', 'name' => 'Icelandic']);
        Language::firstOrCreate(['3_digit' => 'ido','2_digit' => 'io', 'name' => 'Ido']);
        Language::firstOrCreate(['3_digit' => 'iii','2_digit' => 'ii', 'name' => 'Sichuan Yi; Nuosu']);
        Language::firstOrCreate(['3_digit' => 'ijo','2_digit' => '', 'name' => 'Ijo languages']);
        Language::firstOrCreate(['3_digit' => 'iku','2_digit' => 'iu', 'name' => 'Inuktitut']);
        Language::firstOrCreate(['3_digit' => 'ile','2_digit' => 'ie', 'name' => 'Interlingue; Occidental']);
        Language::firstOrCreate(['3_digit' => 'ilo','2_digit' => '', 'name' => 'Iloko']);
        Language::firstOrCreate(['3_digit' => 'ina','2_digit' => 'ia', 'name' => 'Interlingua (International Auxiliary Language Association)']);
        Language::firstOrCreate(['3_digit' => 'inc','2_digit' => '', 'name' => 'Indic languages']);
        Language::firstOrCreate(['3_digit' => 'ind','2_digit' => 'id', 'name' => 'Indonesian']);
        Language::firstOrCreate(['3_digit' => 'ine','2_digit' => '', 'name' => 'Indo-European languages']);
        Language::firstOrCreate(['3_digit' => 'inh','2_digit' => '', 'name' => 'Ingush']);
        Language::firstOrCreate(['3_digit' => 'ipk','2_digit' => 'ik', 'name' => 'Inupiaq']);
        Language::firstOrCreate(['3_digit' => 'ira','2_digit' => '', 'name' => 'Iranian languages']);
        Language::firstOrCreate(['3_digit' => 'iro','2_digit' => '', 'name' => 'Iroquoian languages']);
        Language::firstOrCreate(['3_digit' => 'ice','2_digit' => 'is', 'name' => 'Icelandic']);
        Language::firstOrCreate(['3_digit' => 'isl','2_digit' => 'is', 'name' => 'Icelandic']);
        Language::firstOrCreate(['3_digit' => 'ita','2_digit' => 'it', 'name' => 'Italian']);
        Language::firstOrCreate(['3_digit' => 'jav','2_digit' => 'jv', 'name' => 'Javanese']);
        Language::firstOrCreate(['3_digit' => 'jbo','2_digit' => '', 'name' => 'Lojban']);
        Language::firstOrCreate(['3_digit' => 'jpn','2_digit' => 'ja', 'name' => 'Japanese']);
        Language::firstOrCreate(['3_digit' => 'jpr','2_digit' => '', 'name' => 'Judeo-Persian']);
        Language::firstOrCreate(['3_digit' => 'jrb','2_digit' => '', 'name' => 'Judeo-Arabic']);
        Language::firstOrCreate(['3_digit' => 'kaa','2_digit' => '', 'name' => 'Kara-Kalpak']);
        Language::firstOrCreate(['3_digit' => 'kab','2_digit' => '', 'name' => 'Kabyle']);
        Language::firstOrCreate(['3_digit' => 'kac','2_digit' => '', 'name' => 'Kachin; Jingpho']);
        Language::firstOrCreate(['3_digit' => 'kal','2_digit' => 'kl', 'name' => 'Kalaallisut; Greenlandic']);
        Language::firstOrCreate(['3_digit' => 'kam','2_digit' => '', 'name' => 'Kamba']);
        Language::firstOrCreate(['3_digit' => 'kan','2_digit' => 'kn', 'name' => 'Kannada']);
        Language::firstOrCreate(['3_digit' => 'kar','2_digit' => '', 'name' => 'Karen languages']);
        Language::firstOrCreate(['3_digit' => 'kas','2_digit' => 'ks', 'name' => 'Kashmiri']);
        Language::firstOrCreate(['3_digit' => 'geo','2_digit' => 'ka', 'name' => 'Georgian']);
        Language::firstOrCreate(['3_digit' => 'kat','2_digit' => 'ka', 'name' => 'Georgian']);
        Language::firstOrCreate(['3_digit' => 'kau','2_digit' => 'kr', 'name' => 'Kanuri']);
        Language::firstOrCreate(['3_digit' => 'kaw','2_digit' => '', 'name' => 'Kawi']);
        Language::firstOrCreate(['3_digit' => 'kaz','2_digit' => 'kk', 'name' => 'Kazakh']);
        Language::firstOrCreate(['3_digit' => 'kbd','2_digit' => '', 'name' => 'Kabardian']);
        Language::firstOrCreate(['3_digit' => 'kha','2_digit' => '', 'name' => 'Khasi']);
        Language::firstOrCreate(['3_digit' => 'khi','2_digit' => '', 'name' => 'Khoisan languages']);
        Language::firstOrCreate(['3_digit' => 'khm','2_digit' => 'km', 'name' => 'Central Khmer']);
        Language::firstOrCreate(['3_digit' => 'kho','2_digit' => '', 'name' => 'Khotanese; Sakan']);
        Language::firstOrCreate(['3_digit' => 'kik','2_digit' => 'ki', 'name' => 'Kikuyu; Gikuyu']);
        Language::firstOrCreate(['3_digit' => 'kin','2_digit' => 'rw', 'name' => 'Kinyarwanda']);
        Language::firstOrCreate(['3_digit' => 'kir','2_digit' => 'ky', 'name' => 'Kirghiz; Kyrgyz']);
        Language::firstOrCreate(['3_digit' => 'kmb','2_digit' => '', 'name' => 'Kimbundu']);
        Language::firstOrCreate(['3_digit' => 'kok','2_digit' => '', 'name' => 'Konkani']);
        Language::firstOrCreate(['3_digit' => 'kom','2_digit' => 'kv', 'name' => 'Komi']);
        Language::firstOrCreate(['3_digit' => 'kon','2_digit' => 'kg', 'name' => 'Kongo']);
        Language::firstOrCreate(['3_digit' => 'kor','2_digit' => 'ko', 'name' => 'Korean']);
        Language::firstOrCreate(['3_digit' => 'kos','2_digit' => '', 'name' => 'Kosraean']);
        Language::firstOrCreate(['3_digit' => 'kpe','2_digit' => '', 'name' => 'Kpelle']);
        Language::firstOrCreate(['3_digit' => 'krc','2_digit' => '', 'name' => 'Karachay-Balkar']);
        Language::firstOrCreate(['3_digit' => 'krl','2_digit' => '', 'name' => 'Karelian']);
        Language::firstOrCreate(['3_digit' => 'kro','2_digit' => '', 'name' => 'Kru languages']);
        Language::firstOrCreate(['3_digit' => 'kru','2_digit' => '', 'name' => 'Kurukh']);
        Language::firstOrCreate(['3_digit' => 'kua','2_digit' => 'kj', 'name' => 'Kuanyama; Kwanyama']);
        Language::firstOrCreate(['3_digit' => 'kum','2_digit' => '', 'name' => 'Kumyk']);
        Language::firstOrCreate(['3_digit' => 'kur','2_digit' => 'ku', 'name' => 'Kurdish']);
        Language::firstOrCreate(['3_digit' => 'kut','2_digit' => '', 'name' => 'Kutenai']);
        Language::firstOrCreate(['3_digit' => 'lad','2_digit' => '', 'name' => 'Ladino']);
        Language::firstOrCreate(['3_digit' => 'lah','2_digit' => '', 'name' => 'Lahnda']);
        Language::firstOrCreate(['3_digit' => 'lam','2_digit' => '', 'name' => 'Lamba']);
        Language::firstOrCreate(['3_digit' => 'lao','2_digit' => 'lo', 'name' => 'Lao']);
        Language::firstOrCreate(['3_digit' => 'lat','2_digit' => 'la', 'name' => 'Latin']);
        Language::firstOrCreate(['3_digit' => 'lav','2_digit' => 'lv', 'name' => 'Latvian']);
        Language::firstOrCreate(['3_digit' => 'lez','2_digit' => '', 'name' => 'Lezghian']);
        Language::firstOrCreate(['3_digit' => 'lim','2_digit' => 'li', 'name' => 'Limburgan; Limburger; Limburgish']);
        Language::firstOrCreate(['3_digit' => 'lin','2_digit' => 'ln', 'name' => 'Lingala']);
        Language::firstOrCreate(['3_digit' => 'lit','2_digit' => 'lt', 'name' => 'Lithuanian']);
        Language::firstOrCreate(['3_digit' => 'lol','2_digit' => '', 'name' => 'Mongo']);
        Language::firstOrCreate(['3_digit' => 'loz','2_digit' => '', 'name' => 'Lozi']);
        Language::firstOrCreate(['3_digit' => 'ltz','2_digit' => 'lb', 'name' => 'Luxembourgish; Letzeburgesch']);
        Language::firstOrCreate(['3_digit' => 'lua','2_digit' => '', 'name' => 'Luba-Lulua']);
        Language::firstOrCreate(['3_digit' => 'lub','2_digit' => 'lu', 'name' => 'Luba-Katanga']);
        Language::firstOrCreate(['3_digit' => 'lug','2_digit' => 'lg', 'name' => 'Ganda']);
        Language::firstOrCreate(['3_digit' => 'lui','2_digit' => '', 'name' => 'Luiseno']);
        Language::firstOrCreate(['3_digit' => 'lun','2_digit' => '', 'name' => 'Lunda']);
        Language::firstOrCreate(['3_digit' => 'luo','2_digit' => '', 'name' => 'Luo (Kenya and Tanzania)']);
        Language::firstOrCreate(['3_digit' => 'lus','2_digit' => '', 'name' => 'Lushai']);
        Language::firstOrCreate(['3_digit' => 'mac','2_digit' => 'mk', 'name' => 'Macedonian']);
        Language::firstOrCreate(['3_digit' => 'mkd','2_digit' => 'mk', 'name' => 'Macedonian']);
        Language::firstOrCreate(['3_digit' => 'mad','2_digit' => '', 'name' => 'Madurese']);
        Language::firstOrCreate(['3_digit' => 'mag','2_digit' => '', 'name' => 'Magahi']);
        Language::firstOrCreate(['3_digit' => 'mah','2_digit' => 'mh', 'name' => 'Marshallese']);
        Language::firstOrCreate(['3_digit' => 'mai','2_digit' => '', 'name' => 'Maithili']);
        Language::firstOrCreate(['3_digit' => 'mak','2_digit' => '', 'name' => 'Makasar']);
        Language::firstOrCreate(['3_digit' => 'mal','2_digit' => 'ml', 'name' => 'Malayalam']);
        Language::firstOrCreate(['3_digit' => 'man','2_digit' => '', 'name' => 'Mandingo']);
        Language::firstOrCreate(['3_digit' => 'mao','2_digit' => 'mi', 'name' => 'Maori']);
        Language::firstOrCreate(['3_digit' => 'mri','2_digit' => 'mi', 'name' => 'Maori']);
        Language::firstOrCreate(['3_digit' => 'map','2_digit' => '', 'name' => 'Austronesian languages']);
        Language::firstOrCreate(['3_digit' => 'mar','2_digit' => 'mr', 'name' => 'Marathi']);
        Language::firstOrCreate(['3_digit' => 'mas','2_digit' => '', 'name' => 'Masai']);
        Language::firstOrCreate(['3_digit' => 'May','2_digit' => 'ms', 'name' => 'Malay']);
        Language::firstOrCreate(['3_digit' => 'msa','2_digit' => 'ms', 'name' => 'Malay']);
        Language::firstOrCreate(['3_digit' => 'mdf','2_digit' => '', 'name' => 'Moksha']);
        Language::firstOrCreate(['3_digit' => 'mdr','2_digit' => '', 'name' => 'Mandar']);
        Language::firstOrCreate(['3_digit' => 'men','2_digit' => '', 'name' => 'Mende']);
        Language::firstOrCreate(['3_digit' => 'mga','2_digit' => '', 'name' => 'Irish, Middle (900-1200)']);
        Language::firstOrCreate(['3_digit' => 'mic','2_digit' => '', 'name' => 'Mi\'kmaq; Micmac']);
        Language::firstOrCreate(['3_digit' => 'min','2_digit' => '', 'name' => 'Minangkabau']);
        Language::firstOrCreate(['3_digit' => 'mis','2_digit' => '', 'name' => 'Uncoded languages']);
        Language::firstOrCreate(['3_digit' => 'mac','2_digit' => 'mk', 'name' => 'Macedonian']);
        Language::firstOrCreate(['3_digit' => 'mkd','2_digit' => 'mk', 'name' => 'Macedonian']);
        Language::firstOrCreate(['3_digit' => 'mkh','2_digit' => '', 'name' => 'Mon-Khmer languages']);
        Language::firstOrCreate(['3_digit' => 'mlg','2_digit' => 'mg', 'name' => 'Malagasy']);
        Language::firstOrCreate(['3_digit' => 'mlt','2_digit' => 'mt', 'name' => 'Maltese']);
        Language::firstOrCreate(['3_digit' => 'mnc','2_digit' => '', 'name' => 'Manchu']);
        Language::firstOrCreate(['3_digit' => 'mni','2_digit' => '', 'name' => 'Manipuri']);
        Language::firstOrCreate(['3_digit' => 'mno','2_digit' => '', 'name' => 'Manobo languages']);
        Language::firstOrCreate(['3_digit' => 'moh','2_digit' => '', 'name' => 'Mohawk']);
        Language::firstOrCreate(['3_digit' => 'mon','2_digit' => 'mn', 'name' => 'Mongolian']);
        Language::firstOrCreate(['3_digit' => 'mos','2_digit' => '', 'name' => 'Mossi']);
        Language::firstOrCreate(['3_digit' => 'mao','2_digit' => 'mi', 'name' => 'Maori']);
        Language::firstOrCreate(['3_digit' => 'mri','2_digit' => 'mi', 'name' => 'Maori']);
        Language::firstOrCreate(['3_digit' => 'May','2_digit' => 'ms', 'name' => 'Malay']);
        Language::firstOrCreate(['3_digit' => 'msa','2_digit' => 'ms', 'name' => 'Malay']);
        Language::firstOrCreate(['3_digit' => 'mul','2_digit' => '', 'name' => 'Multiple languages']);
        Language::firstOrCreate(['3_digit' => 'mun','2_digit' => '', 'name' => 'Munda languages']);
        Language::firstOrCreate(['3_digit' => 'mus','2_digit' => '', 'name' => 'Creek']);
        Language::firstOrCreate(['3_digit' => 'mwl','2_digit' => '', 'name' => 'Mirandese']);
        Language::firstOrCreate(['3_digit' => 'mwr','2_digit' => '', 'name' => 'Marwari']);
        Language::firstOrCreate(['3_digit' => 'bur','2_digit' => 'my', 'name' => 'Burmese']);
        Language::firstOrCreate(['3_digit' => 'mya','2_digit' => 'my', 'name' => 'Burmese']);
        Language::firstOrCreate(['3_digit' => 'myn','2_digit' => '', 'name' => 'Mayan languages']);
        Language::firstOrCreate(['3_digit' => 'myv','2_digit' => '', 'name' => 'Erzya']);
        Language::firstOrCreate(['3_digit' => 'nah','2_digit' => '', 'name' => 'Nahuatl languages']);
        Language::firstOrCreate(['3_digit' => 'nai','2_digit' => '', 'name' => 'North American Indian languages']);
        Language::firstOrCreate(['3_digit' => 'nap','2_digit' => '', 'name' => 'Neapolitan']);
        Language::firstOrCreate(['3_digit' => 'nau','2_digit' => 'na', 'name' => 'Nauru']);
        Language::firstOrCreate(['3_digit' => 'nav','2_digit' => 'nv', 'name' => 'Navajo; Navaho']);
        Language::firstOrCreate(['3_digit' => 'nbl','2_digit' => 'nr', 'name' => 'Ndebele, South; South Ndebele']);
        Language::firstOrCreate(['3_digit' => 'nde','2_digit' => 'nd', 'name' => 'Ndebele, North; North Ndebele']);
        Language::firstOrCreate(['3_digit' => 'ndo','2_digit' => 'ng', 'name' => 'Ndonga']);
        Language::firstOrCreate(['3_digit' => 'nds','2_digit' => '', 'name' => 'Low German; Low Saxon; German, Low; Saxon, Low']);
        Language::firstOrCreate(['3_digit' => 'nep','2_digit' => 'ne', 'name' => 'Nepali']);
        Language::firstOrCreate(['3_digit' => 'new','2_digit' => '', 'name' => 'Nepal Bhasa; Newari']);
        Language::firstOrCreate(['3_digit' => 'nia','2_digit' => '', 'name' => 'Nias']);
        Language::firstOrCreate(['3_digit' => 'nic','2_digit' => '', 'name' => 'Niger-Kordofanian languages']);
        Language::firstOrCreate(['3_digit' => 'niu','2_digit' => '', 'name' => 'Niuean']);
        Language::firstOrCreate(['3_digit' => 'dut','2_digit' => 'nl', 'name' => 'Dutch; Flemish']);
        Language::firstOrCreate(['3_digit' => 'nld','2_digit' => 'nl', 'name' => 'Dutch; Flemish']);
        Language::firstOrCreate(['3_digit' => 'nno','2_digit' => 'nn', 'name' => 'Norwegian Nynorsk; Nynorsk, Norwegian']);
        Language::firstOrCreate(['3_digit' => 'nob','2_digit' => 'nb', 'name' => 'Bokmal, Norwegian; Norwegian Bokmal']);
        Language::firstOrCreate(['3_digit' => 'nog','2_digit' => '', 'name' => 'Nogai']);
        Language::firstOrCreate(['3_digit' => 'non','2_digit' => '', 'name' => 'Norse, Old']);
        Language::firstOrCreate(['3_digit' => 'nor','2_digit' => 'no', 'name' => 'Norwegian']);
        Language::firstOrCreate(['3_digit' => 'nqo','2_digit' => '', 'name' => 'N\'Ko']);
        Language::firstOrCreate(['3_digit' => 'nso','2_digit' => '', 'name' => 'Pedi; Sepedi; Northern Sotho']);
        Language::firstOrCreate(['3_digit' => 'nub','2_digit' => '', 'name' => 'Nubian languages']);
        Language::firstOrCreate(['3_digit' => 'nwc','2_digit' => '', 'name' => 'Classical Newari; Old Newari; Classical Nepal Bhasa']);
        Language::firstOrCreate(['3_digit' => 'nya','2_digit' => 'ny', 'name' => 'Chichewa; Chewa; Nyanja']);
        Language::firstOrCreate(['3_digit' => 'nym','2_digit' => '', 'name' => 'Nyamwezi']);
        Language::firstOrCreate(['3_digit' => 'nyn','2_digit' => '', 'name' => 'Nyankole']);
        Language::firstOrCreate(['3_digit' => 'nyo','2_digit' => '', 'name' => 'Nyoro']);
        Language::firstOrCreate(['3_digit' => 'nzi','2_digit' => '', 'name' => 'Nzima']);
        Language::firstOrCreate(['3_digit' => 'oci','2_digit' => 'oc', 'name' => 'Occitan (post 1500)']);
        Language::firstOrCreate(['3_digit' => 'oji','2_digit' => 'oj', 'name' => 'Ojibwa']);
        Language::firstOrCreate(['3_digit' => 'ori','2_digit' => 'or', 'name' => 'Oriya']);
        Language::firstOrCreate(['3_digit' => 'orm','2_digit' => 'om', 'name' => 'Oromo']);
        Language::firstOrCreate(['3_digit' => 'osa','2_digit' => '', 'name' => 'Osage']);
        Language::firstOrCreate(['3_digit' => 'oss','2_digit' => 'os', 'name' => 'Ossetian; Ossetic']);
        Language::firstOrCreate(['3_digit' => 'ota','2_digit' => '', 'name' => 'Turkish, Ottoman (1500-1928)']);
        Language::firstOrCreate(['3_digit' => 'oto','2_digit' => '', 'name' => 'Otomian languages']);
        Language::firstOrCreate(['3_digit' => 'paa','2_digit' => '', 'name' => 'Papuan languages']);
        Language::firstOrCreate(['3_digit' => 'pag','2_digit' => '', 'name' => 'Pangasinan']);
        Language::firstOrCreate(['3_digit' => 'pal','2_digit' => '', 'name' => 'Pahlavi']);
        Language::firstOrCreate(['3_digit' => 'pam','2_digit' => '', 'name' => 'Pampanga; Kapampangan']);
        Language::firstOrCreate(['3_digit' => 'pan','2_digit' => 'pa', 'name' => 'Panjabi; Punjabi']);
        Language::firstOrCreate(['3_digit' => 'pap','2_digit' => '', 'name' => 'Papiamento']);
        Language::firstOrCreate(['3_digit' => 'pau','2_digit' => '', 'name' => 'Palauan']);
        Language::firstOrCreate(['3_digit' => 'peo','2_digit' => '', 'name' => 'Persian, Old (ca.600-400 B.C.)']);
        Language::firstOrCreate(['3_digit' => 'per','2_digit' => 'fa', 'name' => 'Persian']);
        Language::firstOrCreate(['3_digit' => 'fas','2_digit' => 'fa', 'name' => 'Persian']);
        Language::firstOrCreate(['3_digit' => 'phi','2_digit' => '', 'name' => 'Philippine languages']);
        Language::firstOrCreate(['3_digit' => 'phn','2_digit' => '', 'name' => 'Phoenician']);
        Language::firstOrCreate(['3_digit' => 'pli','2_digit' => 'pi', 'name' => 'Pali']);
        Language::firstOrCreate(['3_digit' => 'pol','2_digit' => 'pl', 'name' => 'Polish']);
        Language::firstOrCreate(['3_digit' => 'pon','2_digit' => '', 'name' => 'Pohnpeian']);
        Language::firstOrCreate(['3_digit' => 'por','2_digit' => 'pt', 'name' => 'Portuguese']);
        Language::firstOrCreate(['3_digit' => 'pra','2_digit' => '', 'name' => 'Prakrit languages']);
        Language::firstOrCreate(['3_digit' => 'pro','2_digit' => '', 'name' => 'Provencal, Old (to 1500);Occitan, Old (to 1500)']);
        Language::firstOrCreate(['3_digit' => 'pus','2_digit' => 'ps', 'name' => 'Pushto; Pashto']);
        Language::firstOrCreate(['3_digit' => 'qaa','2_digit' => '', 'name' => 'Reserved for local use']);
        Language::firstOrCreate(['3_digit' => 'que','2_digit' => 'qu', 'name' => 'Quechua']);
        Language::firstOrCreate(['3_digit' => 'raj','2_digit' => '', 'name' => 'Rajasthani']);
        Language::firstOrCreate(['3_digit' => 'rap','2_digit' => '', 'name' => 'Rapanui']);
        Language::firstOrCreate(['3_digit' => 'rar','2_digit' => '', 'name' => 'Rarotongan; Cook Islands Maori']);
        Language::firstOrCreate(['3_digit' => 'roa','2_digit' => '', 'name' => 'Romance languages']);
        Language::firstOrCreate(['3_digit' => 'roh','2_digit' => 'rm', 'name' => 'Romansh']);
        Language::firstOrCreate(['3_digit' => 'rom','2_digit' => '', 'name' => 'Romany']);
        Language::firstOrCreate(['3_digit' => 'rum','2_digit' => 'ro', 'name' => 'Romanian; Moldavian; Moldovan']);
        Language::firstOrCreate(['3_digit' => 'ron','2_digit' => 'ro', 'name' => 'Romanian; Moldavian; Moldovan']);
        Language::firstOrCreate(['3_digit' => 'run','2_digit' => 'rn', 'name' => 'Rundi']);
        Language::firstOrCreate(['3_digit' => 'rup','2_digit' => '', 'name' => 'Aromanian; Arumanian; Macedo-Romanian']);
        Language::firstOrCreate(['3_digit' => 'rus','2_digit' => 'ru', 'name' => 'Russian']);
        Language::firstOrCreate(['3_digit' => 'sad','2_digit' => '', 'name' => 'Sandawe']);
        Language::firstOrCreate(['3_digit' => 'sag','2_digit' => 'sg', 'name' => 'Sango']);
        Language::firstOrCreate(['3_digit' => 'sah','2_digit' => '', 'name' => 'Yakut']);
        Language::firstOrCreate(['3_digit' => 'sai','2_digit' => '', 'name' => 'South American Indian languages']);
        Language::firstOrCreate(['3_digit' => 'sal','2_digit' => '', 'name' => 'Salishan languages']);
        Language::firstOrCreate(['3_digit' => 'sam','2_digit' => '', 'name' => 'Samaritan Aramaic']);
        Language::firstOrCreate(['3_digit' => 'san','2_digit' => 'sa', 'name' => 'Sanskrit']);
        Language::firstOrCreate(['3_digit' => 'sas','2_digit' => '', 'name' => 'Sasak']);
        Language::firstOrCreate(['3_digit' => 'sat','2_digit' => '', 'name' => 'Santali']);
        Language::firstOrCreate(['3_digit' => 'scn','2_digit' => '', 'name' => 'Sicilian']);
        Language::firstOrCreate(['3_digit' => 'sco','2_digit' => '', 'name' => 'Scots']);
        Language::firstOrCreate(['3_digit' => 'sel','2_digit' => '', 'name' => 'Selkup']);
        Language::firstOrCreate(['3_digit' => 'sem','2_digit' => '', 'name' => 'Semitic languages']);
        Language::firstOrCreate(['3_digit' => 'sga','2_digit' => '', 'name' => 'Irish, Old (to 900)']);
        Language::firstOrCreate(['3_digit' => 'sgn','2_digit' => '', 'name' => 'Sign Languages']);
        Language::firstOrCreate(['3_digit' => 'shn','2_digit' => '', 'name' => 'Shan']);
        Language::firstOrCreate(['3_digit' => 'sid','2_digit' => '', 'name' => 'Sidamo']);
        Language::firstOrCreate(['3_digit' => 'sin','2_digit' => 'si', 'name' => 'Sinhala; Sinhalese']);
        Language::firstOrCreate(['3_digit' => 'sio','2_digit' => '', 'name' => 'Siouan languages']);
        Language::firstOrCreate(['3_digit' => 'sit','2_digit' => '', 'name' => 'Sino-Tibetan languages']);
        Language::firstOrCreate(['3_digit' => 'sla','2_digit' => '', 'name' => 'Slavic languages']);
        Language::firstOrCreate(['3_digit' => 'slo','2_digit' => 'sk', 'name' => 'Slovak']);
        Language::firstOrCreate(['3_digit' => 'slk','2_digit' => 'sk', 'name' => 'Slovak']);
        Language::firstOrCreate(['3_digit' => 'slv','2_digit' => 'sl', 'name' => 'Slovenian']);
        Language::firstOrCreate(['3_digit' => 'sma','2_digit' => '', 'name' => 'Southern Sami']);
        Language::firstOrCreate(['3_digit' => 'sme','2_digit' => 'se', 'name' => 'Northern Sami']);
        Language::firstOrCreate(['3_digit' => 'smi','2_digit' => '', 'name' => 'Sami languages']);
        Language::firstOrCreate(['3_digit' => 'smj','2_digit' => '', 'name' => 'Lule Sami']);
        Language::firstOrCreate(['3_digit' => 'smn','2_digit' => '', 'name' => 'Inari Sami']);
        Language::firstOrCreate(['3_digit' => 'smo','2_digit' => 'sm', 'name' => 'Samoan']);
        Language::firstOrCreate(['3_digit' => 'sms','2_digit' => '', 'name' => 'Skolt Sami']);
        Language::firstOrCreate(['3_digit' => 'sna','2_digit' => 'sn', 'name' => 'Shona']);
        Language::firstOrCreate(['3_digit' => 'snd','2_digit' => 'sd', 'name' => 'Sindhi']);
        Language::firstOrCreate(['3_digit' => 'snk','2_digit' => '', 'name' => 'Soninke']);
        Language::firstOrCreate(['3_digit' => 'sog','2_digit' => '', 'name' => 'Sogdian']);
        Language::firstOrCreate(['3_digit' => 'som','2_digit' => 'so', 'name' => 'Somali']);
        Language::firstOrCreate(['3_digit' => 'son','2_digit' => '', 'name' => 'Songhai languages']);
        Language::firstOrCreate(['3_digit' => 'sot','2_digit' => 'st', 'name' => 'Sotho, Southern']);
        Language::firstOrCreate(['3_digit' => 'spa','2_digit' => 'es', 'name' => 'Spanish; Castilian']);
        Language::firstOrCreate(['3_digit' => 'alb','2_digit' => 'sq', 'name' => 'Albanian']);
        Language::firstOrCreate(['3_digit' => 'sqi','2_digit' => 'sq', 'name' => 'Albanian']);
        Language::firstOrCreate(['3_digit' => 'srd','2_digit' => 'sc', 'name' => 'Sardinian']);
        Language::firstOrCreate(['3_digit' => 'srn','2_digit' => '', 'name' => 'Sranan Tongo']);
        Language::firstOrCreate(['3_digit' => 'srp','2_digit' => 'sr', 'name' => 'Serbian']);
        Language::firstOrCreate(['3_digit' => 'srr','2_digit' => '', 'name' => 'Serer']);
        Language::firstOrCreate(['3_digit' => 'ssa','2_digit' => '', 'name' => 'Nilo-Saharan languages']);
        Language::firstOrCreate(['3_digit' => 'ssw','2_digit' => 'ss', 'name' => 'Swati']);
        Language::firstOrCreate(['3_digit' => 'suk','2_digit' => '', 'name' => 'Sukuma']);
        Language::firstOrCreate(['3_digit' => 'sun','2_digit' => 'su', 'name' => 'Sundanese']);
        Language::firstOrCreate(['3_digit' => 'sus','2_digit' => '', 'name' => 'Susu']);
        Language::firstOrCreate(['3_digit' => 'sux','2_digit' => '', 'name' => 'Sumerian']);
        Language::firstOrCreate(['3_digit' => 'swa','2_digit' => 'sw', 'name' => 'Swahili']);
        Language::firstOrCreate(['3_digit' => 'swe','2_digit' => 'sv', 'name' => 'Swedish']);
        Language::firstOrCreate(['3_digit' => 'syc','2_digit' => '', 'name' => 'Classical Syriac']);
        Language::firstOrCreate(['3_digit' => 'syr','2_digit' => '', 'name' => 'Syriac']);
        Language::firstOrCreate(['3_digit' => 'tah','2_digit' => 'ty', 'name' => 'Tahitian']);
        Language::firstOrCreate(['3_digit' => 'tai','2_digit' => '', 'name' => 'Tai languages']);
        Language::firstOrCreate(['3_digit' => 'tam','2_digit' => 'ta', 'name' => 'Tamil']);
        Language::firstOrCreate(['3_digit' => 'tat','2_digit' => 'tt', 'name' => 'Tatar']);
        Language::firstOrCreate(['3_digit' => 'tel','2_digit' => 'te', 'name' => 'Telugu']);
        Language::firstOrCreate(['3_digit' => 'tem','2_digit' => '', 'name' => 'Timne']);
        Language::firstOrCreate(['3_digit' => 'ter','2_digit' => '', 'name' => 'Tereno']);
        Language::firstOrCreate(['3_digit' => 'tet','2_digit' => '', 'name' => 'Tetum']);
        Language::firstOrCreate(['3_digit' => 'tgk','2_digit' => 'tg', 'name' => 'Tajik']);
        Language::firstOrCreate(['3_digit' => 'tgl','2_digit' => 'tl', 'name' => 'Tagalog']);
        Language::firstOrCreate(['3_digit' => 'tha','2_digit' => 'th', 'name' => 'Thai']);
        Language::firstOrCreate(['3_digit' => 'tib','2_digit' => 'bo', 'name' => 'Tibetan']);
        Language::firstOrCreate(['3_digit' => 'bod','2_digit' => 'bo', 'name' => 'Tibetan']);
        Language::firstOrCreate(['3_digit' => 'tig','2_digit' => '', 'name' => 'Tigre']);
        Language::firstOrCreate(['3_digit' => 'tir','2_digit' => 'ti', 'name' => 'Tigrinya']);
        Language::firstOrCreate(['3_digit' => 'tiv','2_digit' => '', 'name' => 'Tiv']);
        Language::firstOrCreate(['3_digit' => 'tkl','2_digit' => '', 'name' => 'Tokelau']);
        Language::firstOrCreate(['3_digit' => 'tlh','2_digit' => '', 'name' => 'Klingon; tlhIngan-Hol']);
        Language::firstOrCreate(['3_digit' => 'tli','2_digit' => '', 'name' => 'Tlingit']);
        Language::firstOrCreate(['3_digit' => 'tmh','2_digit' => '', 'name' => 'Tamashek']);
        Language::firstOrCreate(['3_digit' => 'tog','2_digit' => '', 'name' => 'Tonga (Nyasa)']);
        Language::firstOrCreate(['3_digit' => 'ton','2_digit' => 'to', 'name' => 'Tonga (Tonga Islands)']);
        Language::firstOrCreate(['3_digit' => 'tpi','2_digit' => '', 'name' => 'Tok Pisin']);
        Language::firstOrCreate(['3_digit' => 'tsi','2_digit' => '', 'name' => 'Tsimshian']);
        Language::firstOrCreate(['3_digit' => 'tsn','2_digit' => 'tn', 'name' => 'Tswana']);
        Language::firstOrCreate(['3_digit' => 'tso','2_digit' => 'ts', 'name' => 'Tsonga']);
        Language::firstOrCreate(['3_digit' => 'tuk','2_digit' => 'tk', 'name' => 'Turkmen']);
        Language::firstOrCreate(['3_digit' => 'tum','2_digit' => '', 'name' => 'Tumbuka']);
        Language::firstOrCreate(['3_digit' => 'tup','2_digit' => '', 'name' => 'Tupi languages']);
        Language::firstOrCreate(['3_digit' => 'tur','2_digit' => 'tr', 'name' => 'Turkish']);
        Language::firstOrCreate(['3_digit' => 'tut','2_digit' => '', 'name' => 'Altaic languages']);
        Language::firstOrCreate(['3_digit' => 'tvl','2_digit' => '', 'name' => 'Tuvalu']);
        Language::firstOrCreate(['3_digit' => 'twi','2_digit' => 'tw', 'name' => 'Twi']);
        Language::firstOrCreate(['3_digit' => 'tyv','2_digit' => '', 'name' => 'Tuvinian']);
        Language::firstOrCreate(['3_digit' => 'udm','2_digit' => '', 'name' => 'Udmurt']);
        Language::firstOrCreate(['3_digit' => 'uga','2_digit' => '', 'name' => 'Ugaritic']);
        Language::firstOrCreate(['3_digit' => 'uig','2_digit' => 'ug', 'name' => 'Uighur; Uyghur']);
        Language::firstOrCreate(['3_digit' => 'ukr','2_digit' => 'uk', 'name' => 'Ukrainian']);
        Language::firstOrCreate(['3_digit' => 'umb','2_digit' => '', 'name' => 'Umbundu']);
        Language::firstOrCreate(['3_digit' => 'und','2_digit' => '', 'name' => 'Undetermined']);
        Language::firstOrCreate(['3_digit' => 'urd','2_digit' => 'ur', 'name' => 'Urdu']);
        Language::firstOrCreate(['3_digit' => 'uzb','2_digit' => 'uz', 'name' => 'Uzbek']);
        Language::firstOrCreate(['3_digit' => 'vai','2_digit' => '', 'name' => 'Vai']);
        Language::firstOrCreate(['3_digit' => 'ven','2_digit' => 've', 'name' => 'Venda']);
        Language::firstOrCreate(['3_digit' => 'vie','2_digit' => 'vi', 'name' => 'Vietnamese']);
        Language::firstOrCreate(['3_digit' => 'vol','2_digit' => 'vo', 'name' => 'Volapük']);
        Language::firstOrCreate(['3_digit' => 'vot','2_digit' => '', 'name' => 'Votic']);
        Language::firstOrCreate(['3_digit' => 'wak','2_digit' => '', 'name' => 'Wakashan languages']);
        Language::firstOrCreate(['3_digit' => 'wal','2_digit' => '', 'name' => 'Wolaitta; Wolaytta']);
        Language::firstOrCreate(['3_digit' => 'war','2_digit' => '', 'name' => 'Waray']);
        Language::firstOrCreate(['3_digit' => 'was','2_digit' => '', 'name' => 'Washo']);
        Language::firstOrCreate(['3_digit' => 'wel','2_digit' => 'cy', 'name' => 'Welsh']);
        Language::firstOrCreate(['3_digit' => 'cym','2_digit' => 'cy', 'name' => 'Welsh']);
        Language::firstOrCreate(['3_digit' => 'wen','2_digit' => '', 'name' => 'Sorbian languages']);
        Language::firstOrCreate(['3_digit' => 'wln','2_digit' => 'wa', 'name' => 'Walloon']);
        Language::firstOrCreate(['3_digit' => 'wol','2_digit' => 'wo', 'name' => 'Wolof']);
        Language::firstOrCreate(['3_digit' => 'xal','2_digit' => '', 'name' => 'Kalmyk; Oirat']);
        Language::firstOrCreate(['3_digit' => 'xho','2_digit' => 'xh', 'name' => 'Xhosa']);
        Language::firstOrCreate(['3_digit' => 'yao','2_digit' => '', 'name' => 'Yao']);
        Language::firstOrCreate(['3_digit' => 'yap','2_digit' => '', 'name' => 'Yapese']);
        Language::firstOrCreate(['3_digit' => 'yid','2_digit' => 'yi', 'name' => 'Yiddish']);
        Language::firstOrCreate(['3_digit' => 'yor','2_digit' => 'yo', 'name' => 'Yoruba']);
        Language::firstOrCreate(['3_digit' => 'ypk','2_digit' => '', 'name' => 'Yupik languages']);
        Language::firstOrCreate(['3_digit' => 'zap','2_digit' => '', 'name' => 'Zapotec']);
        Language::firstOrCreate(['3_digit' => 'zbl','2_digit' => '', 'name' => 'Blissymbols; Blissymbolics; Bliss']);
        Language::firstOrCreate(['3_digit' => 'zen','2_digit' => '', 'name' => 'Zenaga']);
        Language::firstOrCreate(['3_digit' => 'zgh','2_digit' => '', 'name' => 'Standard Moroccan Tamazight']);
        Language::firstOrCreate(['3_digit' => 'zha','2_digit' => 'za', 'name' => 'Zhuang; Chuang']);
        Language::firstOrCreate(['3_digit' => 'chi','2_digit' => 'zh', 'name' => 'Chinese']);
        Language::firstOrCreate(['3_digit' => 'zho','2_digit' => 'zh', 'name' => 'Chinese']);
        Language::firstOrCreate(['3_digit' => 'znd','2_digit' => '', 'name' => 'Zande languages']);
        Language::firstOrCreate(['3_digit' => 'zul','2_digit' => 'zu', 'name' => 'Zulu']);
        Language::firstOrCreate(['3_digit' => 'zun','2_digit' => '', 'name' => 'Zuni']);
        Language::firstOrCreate(['3_digit' => 'zxx','2_digit' => '', 'name' => 'No linguistic content; Not applicable']);
        Language::firstOrCreate(['3_digit' => 'zza','2_digit' => '', 'name' => 'Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki']);
    }
}
