<div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
    <div class="md:grid md:grid-cols-3 md:gap-6">
        <div class="md:col-span-1">
            <div class="px-4 sm:px-0">
                <h3 class="text-lg font-medium leading-6 text-green-900">podcast xml urls</h3>
                <p class="mt-1 text-sm text-green-600">
                    here you can view the xml feeds for your podcast, these are generally provided to spotify & apple to access the information generated by this system. it will allow them to access all of the metadata provided for the podcast in settings and each episode alike.
                </p>
            </div>
        </div>
        <div class="mt-7 md:mt-7 md:col-span-2 text-xs text-green-600">
            here are the url's to access the two different xml feeds.<br />
            spotify: <a href="{{ route('spotify') }}">{{ route('spotify') }}</a><br />
            itunes: <a href="{{ route('itunes') }}">{{ route('itunes') }}</a>
        </div>
    </div>
</div>
